# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sfegrpc import stfl_pb2 as sfegrpc_dot_stfl__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sfegrpc/stfl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/stfl.State/Put',
                request_serializer=sfegrpc_dot_stfl__pb2.KeyValue.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/stfl.State/Exists',
                request_serializer=sfegrpc_dot_stfl__pb2.Key.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/stfl.State/Get',
                request_serializer=sfegrpc_dot_stfl__pb2.Key.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Value.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/stfl.State/Delete',
                request_serializer=sfegrpc_dot_stfl__pb2.Key.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)


class StateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=sfegrpc_dot_stfl__pb2.KeyValue.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=sfegrpc_dot_stfl__pb2.Key.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=sfegrpc_dot_stfl__pb2.Key.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Value.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=sfegrpc_dot_stfl__pb2.Key.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stfl.State', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stfl.State', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class State(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.State/Put',
            sfegrpc_dot_stfl__pb2.KeyValue.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.State/Exists',
            sfegrpc_dot_stfl__pb2.Key.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.State/Get',
            sfegrpc_dot_stfl__pb2.Key.SerializeToString,
            sfegrpc_dot_stfl__pb2.Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.State/Delete',
            sfegrpc_dot_stfl__pb2.Key.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FlowStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/stfl.Flow/Create',
                request_serializer=sfegrpc_dot_stfl__pb2.TopicConfig.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/stfl.Flow/Delete',
                request_serializer=sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/stfl.Flow/Exists',
                request_serializer=sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/stfl.Flow/Shutdown',
                request_serializer=sfegrpc_dot_stfl__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/stfl.Flow/Put',
                request_serializer=sfegrpc_dot_stfl__pb2.TopicValue.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/stfl.Flow/Get',
                request_serializer=sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.ValueOrNone.FromString,
                _registered_method=True)
        self.Join = channel.unary_unary(
                '/stfl.Flow/Join',
                request_serializer=sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
                response_deserializer=sfegrpc_dot_stfl__pb2.Bool.FromString,
                _registered_method=True)


class FlowServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=sfegrpc_dot_stfl__pb2.TopicConfig.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=sfegrpc_dot_stfl__pb2.Topic.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=sfegrpc_dot_stfl__pb2.Topic.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=sfegrpc_dot_stfl__pb2.ShutdownRequest.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=sfegrpc_dot_stfl__pb2.TopicValue.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=sfegrpc_dot_stfl__pb2.Topic.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.ValueOrNone.SerializeToString,
            ),
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=sfegrpc_dot_stfl__pb2.Topic.FromString,
                    response_serializer=sfegrpc_dot_stfl__pb2.Bool.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stfl.Flow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stfl.Flow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Flow(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.Flow/Create',
            sfegrpc_dot_stfl__pb2.TopicConfig.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.Flow/Delete',
            sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.Flow/Exists',
            sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.Flow/Shutdown',
            sfegrpc_dot_stfl__pb2.ShutdownRequest.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.Flow/Put',
            sfegrpc_dot_stfl__pb2.TopicValue.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.Flow/Get',
            sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
            sfegrpc_dot_stfl__pb2.ValueOrNone.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stfl.Flow/Join',
            sfegrpc_dot_stfl__pb2.Topic.SerializeToString,
            sfegrpc_dot_stfl__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
