# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: otvl_general/utils/ope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'otvl_general/utils/ope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cotvl_general/utils/ope.proto\x12\x03ope\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"\x15\n\x04\x42ool\x12\r\n\x05value\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2q\n\x03Ope\x12 \n\x05Ready\x12\n.ope.Empty\x1a\t.ope.Bool\"\x00\x12#\n\x07Version\x12\n.ope.Empty\x1a\n.ope.Value\"\x00\x12#\n\x08Shutdown\x12\n.ope.Value\x1a\t.ope.Bool\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otvl_general.utils.ope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUE']._serialized_start=37
  _globals['_VALUE']._serialized_end=59
  _globals['_BOOL']._serialized_start=61
  _globals['_BOOL']._serialized_end=82
  _globals['_EMPTY']._serialized_start=84
  _globals['_EMPTY']._serialized_end=91
  _globals['_OPE']._serialized_start=93
  _globals['_OPE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
