# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from otvl_general.utils import ope_pb2 as otvl__general_dot_utils_dot_ope__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in otvl_general/utils/ope_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ready = channel.unary_unary(
                '/ope.Ope/Ready',
                request_serializer=otvl__general_dot_utils_dot_ope__pb2.Empty.SerializeToString,
                response_deserializer=otvl__general_dot_utils_dot_ope__pb2.Bool.FromString,
                _registered_method=True)
        self.Version = channel.unary_unary(
                '/ope.Ope/Version',
                request_serializer=otvl__general_dot_utils_dot_ope__pb2.Empty.SerializeToString,
                response_deserializer=otvl__general_dot_utils_dot_ope__pb2.Value.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/ope.Ope/Shutdown',
                request_serializer=otvl__general_dot_utils_dot_ope__pb2.Value.SerializeToString,
                response_deserializer=otvl__general_dot_utils_dot_ope__pb2.Bool.FromString,
                _registered_method=True)


class OpeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=otvl__general_dot_utils_dot_ope__pb2.Empty.FromString,
                    response_serializer=otvl__general_dot_utils_dot_ope__pb2.Bool.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=otvl__general_dot_utils_dot_ope__pb2.Empty.FromString,
                    response_serializer=otvl__general_dot_utils_dot_ope__pb2.Value.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=otvl__general_dot_utils_dot_ope__pb2.Value.FromString,
                    response_serializer=otvl__general_dot_utils_dot_ope__pb2.Bool.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ope.Ope', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ope.Ope', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ope(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ope.Ope/Ready',
            otvl__general_dot_utils_dot_ope__pb2.Empty.SerializeToString,
            otvl__general_dot_utils_dot_ope__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ope.Ope/Version',
            otvl__general_dot_utils_dot_ope__pb2.Empty.SerializeToString,
            otvl__general_dot_utils_dot_ope__pb2.Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ope.Ope/Shutdown',
            otvl__general_dot_utils_dot_ope__pb2.Value.SerializeToString,
            otvl__general_dot_utils_dot_ope__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
