# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: otvl_general/utils/stfl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'otvl_general/utils/stfl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dotvl_general/utils/stfl.proto\x12\x04stfl\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"B\n\x0bTopicConfig\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\x16\n\x0emax_value_size\x18\x03 \x01(\r\"\x16\n\x05Topic\x12\r\n\x05topic\x18\x01 \x01(\t\"3\n\x0fShutdownRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\timmediate\x18\x02 \x01(\x08\"*\n\nTopicValue\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"-\n\x0bValueOrNone\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x0f\n\x07is_none\x18\x02 \x01(\x08\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x15\n\x04\x42ool\x12\r\n\x05value\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\x93\x01\n\x05State\x12#\n\x03Put\x12\x0e.stfl.KeyValue\x1a\n.stfl.Bool\"\x00\x12!\n\x06\x45xists\x12\t.stfl.Key\x1a\n.stfl.Bool\"\x00\x12\x1f\n\x03Get\x12\t.stfl.Key\x1a\x0b.stfl.Value\"\x00\x12!\n\x06\x44\x65lete\x12\t.stfl.Key\x1a\n.stfl.Bool\"\x00\x32\x9f\x02\n\x04\x46low\x12)\n\x06\x43reate\x12\x11.stfl.TopicConfig\x1a\n.stfl.Bool\"\x00\x12#\n\x06\x44\x65lete\x12\x0b.stfl.Topic\x1a\n.stfl.Bool\"\x00\x12#\n\x06\x45xists\x12\x0b.stfl.Topic\x1a\n.stfl.Bool\"\x00\x12/\n\x08Shutdown\x12\x15.stfl.ShutdownRequest\x1a\n.stfl.Bool\"\x00\x12%\n\x03Put\x12\x10.stfl.TopicValue\x1a\n.stfl.Bool\"\x00\x12\'\n\x03Get\x12\x0b.stfl.Topic\x1a\x11.stfl.ValueOrNone\"\x00\x12!\n\x04Join\x12\x0b.stfl.Topic\x1a\n.stfl.Bool\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otvl_general.utils.stfl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEY']._serialized_start=39
  _globals['_KEY']._serialized_end=57
  _globals['_KEYVALUE']._serialized_start=59
  _globals['_KEYVALUE']._serialized_end=97
  _globals['_TOPICCONFIG']._serialized_start=99
  _globals['_TOPICCONFIG']._serialized_end=165
  _globals['_TOPIC']._serialized_start=167
  _globals['_TOPIC']._serialized_end=189
  _globals['_SHUTDOWNREQUEST']._serialized_start=191
  _globals['_SHUTDOWNREQUEST']._serialized_end=242
  _globals['_TOPICVALUE']._serialized_start=244
  _globals['_TOPICVALUE']._serialized_end=286
  _globals['_VALUEORNONE']._serialized_start=288
  _globals['_VALUEORNONE']._serialized_end=333
  _globals['_VALUE']._serialized_start=335
  _globals['_VALUE']._serialized_end=357
  _globals['_BOOL']._serialized_start=359
  _globals['_BOOL']._serialized_end=380
  _globals['_EMPTY']._serialized_start=382
  _globals['_EMPTY']._serialized_end=389
  _globals['_STATE']._serialized_start=392
  _globals['_STATE']._serialized_end=539
  _globals['_FLOW']._serialized_start=542
  _globals['_FLOW']._serialized_end=829
# @@protoc_insertion_point(module_scope)
