# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ddpestore import estore_pb2 as ddpestore_dot_estore__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ddpestore/estore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EstoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exists = channel.unary_unary(
                '/estore.Estore/Exists',
                request_serializer=ddpestore_dot_estore__pb2.Empty.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.Bool.FromString,
                _registered_method=True)
        self.Drop = channel.unary_unary(
                '/estore.Estore/Drop',
                request_serializer=ddpestore_dot_estore__pb2.DropRequest.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.Bool.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/estore.Estore/Create',
                request_serializer=ddpestore_dot_estore__pb2.CreateRequest.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.Bool.FromString,
                _registered_method=True)
        self.CreateCategory = channel.unary_unary(
                '/estore.Estore/CreateCategory',
                request_serializer=ddpestore_dot_estore__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.Empty.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/estore.Estore/StartSession',
                request_serializer=ddpestore_dot_estore__pb2.Empty.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.UUID.FromString,
                _registered_method=True)
        self.RecordEntities = channel.stream_unary(
                '/estore.Estore/RecordEntities',
                request_serializer=ddpestore_dot_estore__pb2.Entity.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.Empty.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/estore.Estore/EndSession',
                request_serializer=ddpestore_dot_estore__pb2.UUID.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.Empty.FromString,
                _registered_method=True)
        self.ReadEntity = channel.unary_unary(
                '/estore.Estore/ReadEntity',
                request_serializer=ddpestore_dot_estore__pb2.ReadEntityRequest.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.ReadEntityResponse.FromString,
                _registered_method=True)
        self.ReadEntities = channel.unary_stream(
                '/estore.Estore/ReadEntities',
                request_serializer=ddpestore_dot_estore__pb2.ReadEntitiesRequest.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.ReadEntityResponse.FromString,
                _registered_method=True)
        self.StartReadSession = channel.unary_unary(
                '/estore.Estore/StartReadSession',
                request_serializer=ddpestore_dot_estore__pb2.ReadSessionRequest.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.UUID.FromString,
                _registered_method=True)
        self.ReadOnSession = channel.unary_stream(
                '/estore.Estore/ReadOnSession',
                request_serializer=ddpestore_dot_estore__pb2.UUID.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.ReadEntityResponse.FromString,
                _registered_method=True)
        self.EndReadSession = channel.unary_unary(
                '/estore.Estore/EndReadSession',
                request_serializer=ddpestore_dot_estore__pb2.UUID.SerializeToString,
                response_deserializer=ddpestore_dot_estore__pb2.Empty.FromString,
                _registered_method=True)


class EstoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordEntities(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartReadSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadOnSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndReadSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=ddpestore_dot_estore__pb2.Empty.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.Bool.SerializeToString,
            ),
            'Drop': grpc.unary_unary_rpc_method_handler(
                    servicer.Drop,
                    request_deserializer=ddpestore_dot_estore__pb2.DropRequest.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.Bool.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=ddpestore_dot_estore__pb2.CreateRequest.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.Bool.SerializeToString,
            ),
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=ddpestore_dot_estore__pb2.CreateCategoryRequest.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.Empty.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=ddpestore_dot_estore__pb2.Empty.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.UUID.SerializeToString,
            ),
            'RecordEntities': grpc.stream_unary_rpc_method_handler(
                    servicer.RecordEntities,
                    request_deserializer=ddpestore_dot_estore__pb2.Entity.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.Empty.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=ddpestore_dot_estore__pb2.UUID.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.Empty.SerializeToString,
            ),
            'ReadEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadEntity,
                    request_deserializer=ddpestore_dot_estore__pb2.ReadEntityRequest.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.ReadEntityResponse.SerializeToString,
            ),
            'ReadEntities': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadEntities,
                    request_deserializer=ddpestore_dot_estore__pb2.ReadEntitiesRequest.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.ReadEntityResponse.SerializeToString,
            ),
            'StartReadSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReadSession,
                    request_deserializer=ddpestore_dot_estore__pb2.ReadSessionRequest.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.UUID.SerializeToString,
            ),
            'ReadOnSession': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadOnSession,
                    request_deserializer=ddpestore_dot_estore__pb2.UUID.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.ReadEntityResponse.SerializeToString,
            ),
            'EndReadSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndReadSession,
                    request_deserializer=ddpestore_dot_estore__pb2.UUID.FromString,
                    response_serializer=ddpestore_dot_estore__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estore.Estore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estore.Estore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Estore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/Exists',
            ddpestore_dot_estore__pb2.Empty.SerializeToString,
            ddpestore_dot_estore__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/Drop',
            ddpestore_dot_estore__pb2.DropRequest.SerializeToString,
            ddpestore_dot_estore__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/Create',
            ddpestore_dot_estore__pb2.CreateRequest.SerializeToString,
            ddpestore_dot_estore__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/CreateCategory',
            ddpestore_dot_estore__pb2.CreateCategoryRequest.SerializeToString,
            ddpestore_dot_estore__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/StartSession',
            ddpestore_dot_estore__pb2.Empty.SerializeToString,
            ddpestore_dot_estore__pb2.UUID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordEntities(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/estore.Estore/RecordEntities',
            ddpestore_dot_estore__pb2.Entity.SerializeToString,
            ddpestore_dot_estore__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/EndSession',
            ddpestore_dot_estore__pb2.UUID.SerializeToString,
            ddpestore_dot_estore__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/ReadEntity',
            ddpestore_dot_estore__pb2.ReadEntityRequest.SerializeToString,
            ddpestore_dot_estore__pb2.ReadEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/estore.Estore/ReadEntities',
            ddpestore_dot_estore__pb2.ReadEntitiesRequest.SerializeToString,
            ddpestore_dot_estore__pb2.ReadEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartReadSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/StartReadSession',
            ddpestore_dot_estore__pb2.ReadSessionRequest.SerializeToString,
            ddpestore_dot_estore__pb2.UUID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadOnSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/estore.Estore/ReadOnSession',
            ddpestore_dot_estore__pb2.UUID.SerializeToString,
            ddpestore_dot_estore__pb2.ReadEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndReadSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estore.Estore/EndReadSession',
            ddpestore_dot_estore__pb2.UUID.SerializeToString,
            ddpestore_dot_estore__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
