syntax = "proto3";

package estore;

service Estore {
  rpc Exists(Empty) returns (Bool) {}
  rpc Drop(DropRequest) returns (Bool) {}
  rpc Create(CreateRequest) returns (Bool)  {}
  rpc CreateCategory(CreateCategoryRequest) returns (Empty) {}
  rpc StartSession(Empty) returns (UUID) {}
  rpc RecordEntities(stream Entity) returns (Empty) {}
  rpc EndSession(UUID) returns (Empty) {}
  rpc ReadEntity(ReadEntityRequest) returns (ReadEntityResponse) {}
  rpc ReadEntities(ReadEntitiesRequest) returns (stream ReadEntityResponse) {}
  rpc StartReadSession(ReadSessionRequest) returns (UUID) {}
  rpc ReadOnSession(UUID) returns (stream ReadEntityResponse) {}
  rpc EndReadSession(UUID) returns (Empty) {}
}

message DropRequest {
  bool miss_ok = 1;
}

message CreateRequest {
  bool exist_ok = 1;
  bool drop = 2;
  string ddl = 3;
}

message CreateCategoryRequest {
  string label = 1;
  string content = 2;
}

message UUID {
  string uuid = 1;
}

message Entity {
  optional string session_uuid = 1;
  optional string category = 2;
  optional string key = 3;
  optional bytes content = 4;
  optional bytes additional_content = 5;
}

message ReadEntityRequest {
  string category = 1;
  string key = 2;
  optional bool with_additional_content = 3;
}

message ReadEntitiesRequest {
  string category = 1;
  optional bool with_additional_content = 2;
  optional bool with_keys_only = 3;
  repeated string keys = 4;
}

message ReadEntityResponse {
  string key = 1;
  optional bytes content = 2;
  optional bytes additional_content = 3;
  optional string ct_ref = 4;
}

message ReadSessionRequest {
  string category = 1;
  optional bool with_additional_content = 2;
  optional bool with_keys_only = 3;
}

message Bool {
  bool value = 1;
}

message Empty {
}
