FROM debian:13-slim
RUN apt-get update && \
    apt-get install -y python3 python3-venv && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m venv /benv && \
    /benv/bin/pip install build hatchling
