FROM t-ctr.otvl.org/ddpestores-dev:0.2 AS build
WORKDIR /sources
COPY . /sources/
WORKDIR /sources/ddpestores
RUN python3 -m venv /venv && \
 /venv/bin/pip install /build/ddpestores-0.2-py3-none-any.whl


FROM t-ctr.otvl.org/debpy:3.13
RUN mkdir -p /home/dv-user  && \
    chown -R 2001:2001 /home/dv-user
COPY --from=build /venv /venv

USER 2001
WORKDIR /home/dv-user
ENV LANG=en_US.UTF-8
ENV USER=dv-user
ENV HOME=/home/dv-user
ENV SHELL=/bin/bash
ENV PYTHONPATH=/src
