syntax = "proto3";

package stfl;

service State {
  rpc Put(KeyValue) returns (Bool) {}
  rpc Exists(Key) returns (Bool) {}
  rpc Get(Key) returns (Value) {}
  rpc Delete(Key) returns (Bool) {}
}

service Flow {
  rpc Create(TopicConfig) returns (Bool) {}
  rpc Delete(Topic) returns (Bool) {}
  rpc Exists(Topic) returns (Bool) {}
  rpc Shutdown(ShutdownRequest) returns (Bool) {}
  rpc Put(TopicValue) returns (Bool) {}
  rpc Get(Topic) returns (ValueOrNone) {}
  rpc Join(Topic) returns (Bool) {}
}

message Key {
  string key = 1;
}

message KeyValue {
  string key = 1;
  bytes value = 2;
}

message TopicConfig {
  string topic = 1;
  uint32 size = 2;
  uint32 max_value_size = 3;
}

message Topic {
  string topic = 1;
}

message ShutdownRequest {
  string topic = 1;
  bool immediate = 2;
}

message TopicValue {
  string topic = 1;
  bytes value = 2;
}

message ValueOrNone {
  bytes value = 1;
  bool is_none = 2;
}

message Value {
  bytes value = 1;
}

message Bool {
  bool value = 1;
}

message Empty {
}
